// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BQBVCMiFBW9a2RyAzEoVONZEr9q2TfM',
    appId: '1:593867148848:web:84b260f0df3fadfa22a7f5',
    messagingSenderId: '593867148848',
    projectId: 'photos-activities-staging',
    authDomain: 'photos-activities-staging.firebaseapp.com',
    storageBucket: 'photos-activities-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0M2nU7MMrhDKMhdN3g_2SBGOXCsDPN4M',
    appId: '1:593867148848:android:afaf2244424d0b8022a7f5',
    messagingSenderId: '593867148848',
    projectId: 'photos-activities-staging',
    storageBucket: 'photos-activities-staging.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnhtTYlJhlj3jfeWVgsUahL4G94TkzQBI',
    appId: '1:593867148848:ios:2e0e6206814cb4d722a7f5',
    messagingSenderId: '593867148848',
    projectId: 'photos-activities-staging',
    storageBucket: 'photos-activities-staging.firebasestorage.app',
    androidClientId: '593867148848-n93irrju31800s4qskjpvakdaiapedq0.apps.googleusercontent.com',
    iosClientId: '593867148848-30q82vr5tn1vq958nkjdopakhsch3i7u.apps.googleusercontent.com',
    iosBundleId: 'com.billsbayarea.app.staging',
  );
}
