// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3YdjdQBG5gIXMs6iqAOwpgAD1yp2cWIo',
    appId: '1:978335208017:web:dfc6a7677b05a50de79e70',
    messagingSenderId: '978335208017',
    projectId: 'photos-activities-prod',
    authDomain: 'photos-activities-prod.firebaseapp.com',
    storageBucket: 'photos-activities-prod.firebasestorage.app',
    measurementId: 'G-6L14KWJZ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHU6RWVCJr9MMoTJi7etYNRfKesDfnngs',
    appId: '1:978335208017:android:6a85cf7cff319cc6e79e70',
    messagingSenderId: '978335208017',
    projectId: 'photos-activities-prod',
    storageBucket: 'photos-activities-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXClf2-of81jp16rYSXE7dp2hu3kh3u0g',
    appId: '1:978335208017:ios:950d1ff7ba059507e79e70',
    messagingSenderId: '978335208017',
    projectId: 'photos-activities-prod',
    storageBucket: 'photos-activities-prod.firebasestorage.app',
    androidClientId: '978335208017-apbupuh9aekkfhq4jnitibaj25uuhd7l.apps.googleusercontent.com',
    iosClientId: '978335208017-ktkgne3aj7uqmu147unpk0imghq7d8g9.apps.googleusercontent.com',
    iosBundleId: 'com.billsbayarea.app',
  );
}
