// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9PhTh3PeIjpI-TXdRyvLjeZlNmYAt8o',
    appId: '1:1036671893175:web:d8044e2b63db21433bd732',
    messagingSenderId: '1036671893175',
    projectId: 'photos-activities-dev',
    authDomain: 'photos-activities-dev.firebaseapp.com',
    storageBucket: 'photos-activities-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSuCZzlkgjXk3L-rF6g8c1-VSbSA94pWU',
    appId: '1:1036671893175:android:15e319db2a7671963bd732',
    messagingSenderId: '1036671893175',
    projectId: 'photos-activities-dev',
    storageBucket: 'photos-activities-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTckDCf5paqwTKC5pQrDhZET6ZmsT8DBU',
    appId: '1:1036671893175:ios:1a2183343110786a3bd732',
    messagingSenderId: '1036671893175',
    projectId: 'photos-activities-dev',
    storageBucket: 'photos-activities-dev.firebasestorage.app',
    iosBundleId: 'com.billsbayarea.app.dev',
  );
}
